{
  "branches" : ["master"],
  "plugins": [
    "@semantic-release/commit-analyzer",
    "@semantic-release/release-notes-generator",
    ["@saithodev/semantic-release-gitea", {
      "giteaUrl": "http://localhost:3000",
    }],
  ]
}