version: "3.2"

services:
  nexus:
    image: sonatype/nexus3
    ports:
      - "8081:8081"
      - "8082:8082"
    volumes: 
      - "nexus-data:/nexus-data"
    networks:
      - semantic-release
    stop_grace_period: 120s

  
  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - "8080:8080"
      - "50000:50000"
    privileged: true
    user: "jenkins:1000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - "jenkins-data:/var/jenkins_home"
    networks:
      - semantic-release
  jenkins-slave-jdk11:
    image: jenkins/agent:latest-jdk11
    depends_on:
      - jenkins
    networks:
      - semantic-release
    command: java -jar /usr/share/jenkins/agent.jar -jnlpUrl http://jenkins:8080/computer/jenkins-slave-jdk11/slave-agent.jnlp -secret a03d8621fce9475210f8618b48475f7244a155f30c249a6d5a0ff5d4d8692db9 -workDir "/home/jenkins/agent"
  gitea:
    image: gitea/gitea:latest
    environment:
      - USER_UID=1000
      - USER_GID=1000
    restart: always
    networks:
      - semantic-release
    volumes:
      - ./gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3000:3000"
      - "222:22"

volumes:
  jenkins-data:
  nexus-data:  
networks:
  semantic-release:
#  java -jar /usr/share/jenkins/agent.jar -jnlpUrl http://jenkins:8080/computer/jenkins-slave-jdk11/slave-agent.jnlp -secret a03d8621fce9475210f8618b48475f7244a155f30c249a6d5a0ff5d4d8692db9 -workDir "/home/jenkins/agent"
